---
title: "Data Preparation"
author: "Eugene Kiepeeh"
date: "2026-08-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
```

Load raw data from the `tidytuesday`

```{r}
hotels <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2020/2020-02-11/hotels.csv')
```

Remove duplicates
```{r}
clean_hotel_df <- unique(hotels)
```

Remove unnecessary variables and create new variables

```{r}
clean_hotel_df <- clean_hotel_df |>
  # Ensure date is full format
  mutate(arrival_date = glue::glue("{arrival_date_year}-{arrival_date_month}-{arrival_date_day_of_month}"),
         arrival_date = parse_date(arrival_date, format = "%Y-%B-%d")) |>
  relocate(arrival_date, .before = is_canceled) |>
  # Append new variables
  mutate(room_match_flag = ifelse(reserved_room_type == assigned_room_type, 
                                  "Room Match", "Room Change"),
         total_guest = adults + children + babies,
         family_flag = (children + babies) > 0,
         booking_changes_flag = booking_changes > 0) |>
  # Remove features of no importance
  select(-agent, -company, -days_in_waiting_list, -required_car_parking_spaces, -babies, -children, -booking_changes, -previous_cancellations, -previous_bookings_not_canceled)
```

Add new variables related to each transaction
```{r}
clean_hotel_df <- clean_hotel_df |>
  mutate(total_nights = stays_in_weekend_nights + stays_in_week_nights,
         revenue = adr*total_nights, 
         total_adr = adr*total_nights,
         booking_time_flag = case_when( 
                          lead_time <= 7 ~ "0-7", 
                        lead_time >7 & lead_time <=30 ~ "8-30",
         lead_time >30 & lead_time <=90 ~"31-90",
         lead_time >90 ~ "90+"),
         weekend_ratio = round(stays_in_weekend_nights/total_nights,2),
         expected_loss = is_canceled*revenue,
         booking_value = cut(revenue, 
                             breaks = quantile(revenue, 
                                               probs =seq(0,1,0.25), na.rm = TRUE), labels = c("Low Value", "Moderate Value", "High Value", "Premium Value"), include.lowest = TRUE)) |>
  mutate(weekend_ratio = ifelse(weekend_ratio == "NaN", 0, weekend_ratio),
         family_flag = ifelse(is.na(family_flag),0, family_flag),
         booking_urgency = round(1/(lead_time +1),2),
         sameDay_booking = as.character(ifelse(booking_urgency == 1, 1,0)),
         is_canceled = as.factor(is_canceled))
```

Finalize Clean Data

```{r}
write_csv(clean_hotel_df, "~/Documents/00 Working Projects/Hotel Data Analytics/Hotel Analytics/Data/Processed_Data/final_hotel_bookings.csv")
```

