---
title: "Modeling Cancellation Risk"
date: "2026-08-23"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
final_hotel_bookings <- read_csv("~/Documents/00 Working Projects/Hotel Data Analytics/Hotel Analytics/Data/Processed_Data/final_hotel_bookings.csv")
```


```{r}
final_hotel_bookings |> count(hotel)
final_hotel_bookings |> group_by(hotel) |> 
  summarise(mean_canceled = mean((is_canceled), na.rm = T), 
            sd_canceled = sd((is_canceled), na.rm = T), .groups = "drop")
```

```{r}
cancel_mod <- glm(is_canceled ~ hotel, data = final_hotel_bookings, family = binomial(link = "logit"))

summary(cancel_mod)
exp(coef(cancel_mod))

cancel_mod2 <- glm(is_canceled ~ lead_time, data = final_hotel_bookings, family = binomial(link = "logit"))
summary(cancel_mod2)
exp(coef(cancel_mod2))

cancel_mod3 <- glm(is_canceled ~ booking_time_flag, data = final_hotel_bookings, family = binomial(link = "logit"))
summary(cancel_mod3)
exp(coef(cancel_mod3))
```


```{r}
# Cancellation Probabilities by Booking TIme
table(final_hotel_bookings$booking_time_flag,
        as.character(final_hotel_bookings$is_canceled)) |> proportions()
```

```{r}
adr_data <- final_hotel_bookings |> filter(adr == 0)

adr_data2 <- adr_data |> filter(!market_segment %in% c("Online TA", "Offline TA/TO"))
table(adr_data2$market_segment,
        as.character(adr_data2$is_canceled)) |> proportions(margin = 2)

adr_data2 |> group_by(market_segment) |> summarize(bookings = n(),
                                                   pct_cancel = mean(is_canceled), .groups = "drop") |> mutate(comp_stay = 1-pct_cancel)

adr_data |> group_by(distribution_channel) |> summarize(bookings = n(),
                                                   pct_cancel = mean(is_canceled), .groups = "drop") |> mutate(comp_stay = 1-pct_cancel)

adr_data |> group_by(customer_type) |> summarize(bookings = n(),
                                                   pct_cancel = mean(is_canceled), .groups = "drop") |> mutate(comp_stay = 1-pct_cancel)

nights_data <- final_hotel_bookings |> filter(total_nights < 1)

table(final_hotel_bookings$market_segment, final_hotel_bookings$is_canceled)
```


```{r}
final_hotel_bookings |> 
  group_by(market_segment) |>
  summarize(mean_adr = mean(adr, na.rm =T),
            sd = sd(adr, na.rm =T),
            median_adr = median(adr, na.rm = T),
            min_adr = min(adr, na.rm = T),
            mean_nights = mean(total_nights, na.rm = T),
            min_nights = min(total_nights, na.rm = T),
            bookings = n(),
            pct_cancel = mean(is_canceled, na.rm = T))


# see corporate
View(final_hotel_bookings |> filter(market_segment == "Corporate"))
```

